# Feedback on Pilot Mentoring Program
```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE,
               message = FALSE,
               warning = FALSE)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
library(purrr)
library(tibble)
library(DBI)
library(ggmap)
library(likert)
library(mapproj)
library(RColorBrewer)
library(srvyr)
```

# Introduction
```{r include=FALSE}
# Read in the data
data <- readr:: read_csv("https://raw.githubusercontent.com/carpentries/mentoring-program/master/mentoring_feedback.csv")
```

```{r}
# Function that makes a table of counts and percentages
tally_and_perc <- function(df, colname, na.rm = FALSE){
  quo_colname <- enquo(colname)

  df %>% 
    group_by(!!quo_colname) %>% 
    tally() %>% 
    filter(if_else(rep(na.rm, nrow(.)),
                  !is.na(!!quo_colname),
                  as.logical(rep(1, nrow(.))))) %>% 
    mutate(`%` = round(n / sum(n) * 100, 1)) 
}
```

```{r include=FALSE}
support_perc <- 
data %>%
  select(`Support`) %>% 
  gather(col, support_perc) %>% 
  group_by(support_perc) %>% 
  tally_and_perc(support_perc, na.rm = TRUE) %>%
  filter(!is.na(support_perc)) %>% 
  arrange(desc(n)) %>%
  rename(`Support` = support_perc) %>%
print(support_perc, digits = getOption("digits"), quote = FALSE,
      na.print = "", zero.print = "0", justify = "none")
```
```{r}
kable(support_perc)
```

